
package Formularios;

import Clases.consultas;
//import java.util.HashMap;
//import java.util.Map;
import javax.swing.JOptionPane;


public class frmInicio_Session extends javax.swing.JFrame {

//    private Map<String, String> usuarios = new HashMap<>();

    
    public frmInicio_Session() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnIniciar_Session = new javax.swing.JButton();
        jbtnRegistrar = new javax.swing.JButton();
        jtextContraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(112, 145, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Acceso");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(156, 12, 86, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userInicio.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(141, 68, 128, 128);

        jLabel3.setBackground(new java.awt.Color(112, 145, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(156, 288, 88, 26);

        jtextUsuario.setBackground(new java.awt.Color(112, 145, 255));
        jtextUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jtextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jtextUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtextUsuario.setBorder(null);
        jPanel1.add(jtextUsuario);
        jtextUsuario.setBounds(120, 230, 200, 30);

        jSeparator1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(109, 270, 200, 12);

        jLabel4.setBackground(new java.awt.Color(112, 145, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userLabel.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(89, 234, 16, 30);

        jSeparator2.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(109, 356, 200, 11);

        jLabel5.setBackground(new java.awt.Color(112, 145, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/key.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(89, 320, 16, 30);

        jLabel6.setBackground(new java.awt.Color(112, 145, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(163, 202, 77, 26);

        jbtnIniciar_Session.setBackground(new java.awt.Color(60, 78, 234));
        jbtnIniciar_Session.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnIniciar_Session.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIniciar_Session.setText("Iniciar Session");
        jbtnIniciar_Session.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciar_SessionActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIniciar_Session);
        jbtnIniciar_Session.setBounds(129, 403, 137, 25);

        jbtnRegistrar.setBackground(new java.awt.Color(60, 78, 234));
        jbtnRegistrar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jbtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegistrar.setText("Registrar");
        jbtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrar);
        jbtnRegistrar.setBounds(129, 455, 136, 25);

        jtextContraseña.setBackground(new java.awt.Color(112, 145, 255));
        jtextContraseña.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jtextContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jtextContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtextContraseña.setBorder(null);
        jPanel1.add(jtextContraseña);
        jtextContraseña.setBounds(110, 320, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(414, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciar_SessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciar_SessionActionPerformed
        String nombreUsuario = jtextUsuario.getText(); 
        String contrasena = jtextContraseña.getText();
        
        int pos = consultas.verificarInicioSesion(nombreUsuario, contrasena);
        if(pos == -1){
            JOptionPane.showConfirmDialog(this,"Nombre y contraseña  incorrectos");
        }else{
            FrmActividad abrir = new FrmActividad();
            abrir.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jbtnIniciar_SessionActionPerformed

    private void jbtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        frmRegistro f1=new frmRegistro();
        f1.setVisible(true);
    }//GEN-LAST:event_jbtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio_Session().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnIniciar_Session;
    private javax.swing.JButton jbtnRegistrar;
    private javax.swing.JTextField jtextContraseña;
    private javax.swing.JTextField jtextUsuario;
    // End of variables declaration//GEN-END:variables
}
